repos:
  # ruff: lint and format .py and .ipynb files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.13
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt from uv.lock
        entry: bash hooks/export_requirements.sh
        language: system
        files: ^uv\.lock$
