name: "Sphinx: Render docs"

on: 
  push:
    branches:
      - main
      - 'docs/**'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master

